services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    environment:
      NODE_ENV: development

volumes:
  node_modules: {}
