services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab3-api
    ports:
      - '8000:8000'
    env_file:
      - .env.production
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: lab-db
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

volumes:
  postgres_data:
