services:
  db:
    image: postgres:14
    container_name: lab-db-dev
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '4432:5432'
    restart: unless-stopped

volumes:
  postgres_data:
